-- AlterTable
ALTER TABLE `hasil_tugas_mahasiswa` MODIFY `status` ENUM('DISERAHKAN', 'TERLAMBAT', 'DITOLAK', 'DITERIMA', 'DIHAPUS', 'SUCCESS', 'ERROR', 'PENDING', 'NOT_STARTED') NOT NULL DEFAULT 'DISERAHKAN';

-- AlterTable
ALTER TABLE `submission` MODIFY `status_jawaban` ENUM('DISERAHKAN', 'TERLAMBAT', 'DITOLAK', 'DITERIMA', 'DIHAPUS', 'SUCCESS', 'ERROR', 'PENDING', 'NOT_STARTED') NOT NULL;
