-- AlterTable
ALTER TABLE `nilai_tugas` MODIFY `status` ENUM('DISERAHKAN', 'TERLAMBAT', 'DITOLAK', 'DITERIMA', 'DIHAPUS', 'SUCCESS', 'ERROR', 'PENDING') NOT NULL DEFAULT 'DISERAHKAN';

-- AlterTable
ALTER TABLE `submission` ADD COLUMN `status` ENUM('ACCEPTED', 'WRONG_ANSWER', 'TIME_LIMIT_EXCEEDED', 'RUNTIME_ERROR', 'COMPILATION_ERROR', 'PENDING', 'RUNNING', 'JUDGING', 'JUDGE_ERROR', 'PARTIAL') NOT NULL DEFAULT 'PENDING',
    MODIFY `status_jawaban` ENUM('DISERAHKAN', 'TERLAMBAT', 'DITOLAK', 'DITERIMA', 'DIHAPUS', 'SUCCESS', 'ERROR', 'PENDING') NOT NULL;
