-- AlterTable
ALTER TABLE `submission` MODIFY `status` ENUM('ACCEPTED', 'WRONG_ANSWER', 'TIME_LIMIT_EXCEEDED', 'RUNTIME_ERROR', 'COMPILATION_ERROR', 'PENDING', 'RUNNING', 'JUDGING', 'JUDGE_ERROR', 'PARTIAL', 'AC', 'WA', 'TLE', 'RE', 'CE') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `test_case_result` MODIFY `status` ENUM('ACCEPTED', 'WRONG_ANSWER', 'TIME_LIMIT_EXCEEDED', 'RUNTIME_ERROR', 'COMPILATION_ERROR', 'PENDING', 'RUNNING', 'JUDGING', 'JUDGE_ERROR', 'PARTIAL', 'AC', 'WA', 'TLE', 'RE', 'CE') NOT NULL;
